AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: special_inside_parentheses
  SupportedStyles:
    - special_inside_parentheses
    - consistent
    - align_braces
  IndentationWidth: 4

Style/IndentArray:
  EnforcedStyle: special_inside_parentheses
  SupportedStyles:
    - special_inside_parentheses
    - consistent
    - align_braces
  IndentationWidth: 4

Style/BlockComments:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  SupportedStyles:
    - indented
    - indented_relative_to_receiver
  # By default, the indentation width from Style/IndentationWidth is used
  # But it can be overridden by setting this parameter
  IndentationWidth: 4

Style/FrozenStringLiteralComment:
  Enabled: false
