scss_files: 'app/assets/stylesheets/**/*.scss'

exclude: 'app/assets/stylesheets/plugins/**'

linters:
  BorderZero:
    enabled: false

  Indentation:
    severity: warning
    width: 2

  StringQuotes:
    enabled: true
    style: double_quotes

  SpaceBetweenParens:
    enabled: true
    spaces: 1
